AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My NodeJS App

Resources:
  MyNodeJsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: server.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE